### ISSUE TITLE
crash:  invalid memory address or nil pointer dereference [1]

### ISSUE THREAD

**Issue by degeri** [decred/dcrpool#117]
When hitting "https://127.0.0.1:8080/ws" the pool is erroring out . You might need to request "https://127.0.0.1:8080/ws" multiple times to get this.

```

2019-07-26 xx:xx:06.435 [TRC] POOL: Share PPLNS percentages are: (map[string]*big.Rat) (len=2) {
 (string) (len=64) "7aea0a63bb7099e256a5dd367ebdca0f8aaf4332745881d4efa7d339a94802c1": (*big.Rat)(0xc00080f1c0)(7/33),
 (string) (len=64) "193c4b8fd02aaed33ab9c5418ace9bec4047f61f923767bceb5a51c6e368bfa6": (*big.Rat)(0xc00080f0c0)(26/33)
}

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x808326]

goroutine 42 [running]:
github.com/gorilla/websocket.(*Conn).prepWrite(0x0, 0x1, 0xc0001cbd58, 0x40d4e9)
        /home/r00t/go/pkg/mod/github.com/gorilla/websocket@v1.2.0/conn.go:467 +0x26
github.com/gorilla/websocket.(*Conn).NextWriter(0x0, 0x1, 0x30, 0xc000866900, 0x0, 0x0)
        /home/r00t/go/pkg/mod/github.com/gorilla/websocket@v1.2.0/conn.go:488 +0x39
github.com/gorilla/websocket.(*Conn).WriteJSON(0x0, 0xb60fc0, 0xc000866900, 0xc000866900, 0x0)
        /home/r00t/go/pkg/mod/github.com/gorilla/websocket@v1.2.0/json.go:22 +0x49
github.com/decred/dcrpool/gui.(*GUI).SendUpdatedValues(0xc0000ce280, 0xc00032fad0, 0xc000866870, 0x2, 0x2)
        /home/r00t/workdir/dcrpool/gui/websocket.go:62 +0x31d
github.com/decred/dcrpool/gui.(*GUI).Run.func2(0xc0000ce280, 0xe111e0, 0xc0004a2680)
        /home/r00t/workdir/dcrpool/gui/gui.go:283 +0x9d
created by github.com/decred/dcrpool/gui.(*GUI).Run
        /home/r00t/workdir/dcrpool/gui/gui.go:264 +0x75
```

**Comment by degeri** [comment]
Closed by #119
