### ISSUE TITLE
crash: unexpected fault address

### ISSUE THREAD

**Issue by dnldd** [decred/dcrpool#92]
Seems to be originating from `gorilla secure cookie dependency`.
```
Jun 18 12:16:45 coordinator dcrpool[5248]: unexpected fault address 0x7f248a0f42b8
Jun 18 12:16:45 coordinator dcrpool[5248]: fatal error: fault
Jun 18 12:16:45 coordinator dcrpool[5248]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f248a0f42b8 pc=0x4848e7]
Jun 18 12:16:45 coordinator dcrpool[5248]: goroutine 1008 [running]:
Jun 18 12:16:45 coordinator dcrpool[5248]: runtime.throw(0xf35bdd, 0x5)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0002bd688 sp=0xc0002bd658 pc=0x4558e2
Jun 18 12:16:45 coordinator dcrpool[5248]: runtime.sigpanic()
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/runtime/signal_unix.go:397 +0x401 fp=0xc0002bd6b8 sp=0xc0002bd688 pc=0x46b211
Jun 18 12:16:45 coordinator dcrpool[5248]: runtime.memmove(0xc0000c5280, 0x7f248a0f42b8, 0x20)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/runtime/memmove_amd64.s:179 +0x147 fp=0xc0002bd6c0 sp=0xc0002bd6b8 pc=0x4848e7
Jun 18 12:16:45 coordinator dcrpool[5248]: runtime.slicecopy(0xc0000c5280, 0x40, 0x40, 0x7f248a0f42b8, 0x20, 0x20, 0x1, 0xc0002de820)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/runtime/slice.go:227 +0x125 fp=0xc0002bd708 sp=0xc0002bd6c0 pc=0x46c9f5
Jun 18 12:16:45 coordinator dcrpool[5248]: crypto/hmac.New(0x10a4150, 0x7f248a0f42b8, 0x20, 0x20, 0x1, 0x1)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/crypto/hmac/hmac.go:83 +0x44e fp=0xc0002bd7d8 sp=0xc0002bd708 pc=0x733d7e
Jun 18 12:16:45 coordinator dcrpool[5248]: github.com/gorilla/securecookie.(*SecureCookie).Decode(0xc00019aea0, 0xf3c4f8, 0xd, 0xc000176468, 0x90, 0xdd0560, 0xc0004c8c40, 0x1, 0x1199a40)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /home/dnldd/go/pkg/mod/github.com/gorilla/securecookie@v1.1.1/securecookie.go:325 +0x208 fp=0xc0002bd970 sp=0xc0002bd7d8 pc=0xd22428
Jun 18 12:16:45 coordinator dcrpool[5248]: github.com/gorilla/csrf.(*cookieStore).Get(0xc0002de7d0, 0xc00047f000, 0x11, 0x0, 0x0, 0x1199a40, 0xc0004c8c00)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /home/dnldd/go/pkg/mod/github.com/gorilla/csrf@v1.5.1/store.go:44 +0x1db fp=0xc0002bda18 sp=0xc0002bd970 pc=0xd2924b
Jun 18 12:16:45 coordinator dcrpool[5248]: github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc0005af680, 0x11a90a0, 0xc00060f420, 0xc00047f000)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /home/dnldd/go/pkg/mod/github.com/gorilla/csrf@v1.5.1/csrf.go:193 +0xc5 fp=0xc0002bdbb8 sp=0xc0002bda18 pc=0xd26e35
Jun 18 12:16:45 coordinator dcrpool[5248]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc000212000, 0x11a90a0, 0xc00060f420, 0xc0001a6600)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /home/dnldd/go/pkg/mod/github.com/gorilla/mux@v1.7.1/mux.go:212 +0x140 fp=0xc0002bdd08 sp=0xc0002bdbb8 pc=0xd4eaa0
Jun 18 12:16:45 coordinator dcrpool[5248]: net/http.serverHandler.ServeHTTP(0xc000185a00, 0x11a90a0, 0xc00060f420, 0xc0001a6600)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/net/http/server.go:2774 +0xcf fp=0xc0002bdd60 sp=0xc0002bdd08 pc=0xa2aadf
Jun 18 12:16:45 coordinator dcrpool[5248]: net/http.initNPNRequest.ServeHTTP(0xc0001ae700, 0xc000185a00, 0x11a90a0, 0xc00060f420, 0xc0001a6600)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/net/http/server.go:3323 +0xfd fp=0xc0002bdf08 sp=0xc0002bdd60 pc=0xa2d48d
Jun 18 12:16:45 coordinator dcrpool[5248]: net/http.(*initNPNRequest).ServeHTTP(0xc0005ca140, 0x11a90a0, 0xc00060f420, 0xc0001a6600)
Jun 18 12:16:45 coordinator dcrpool[5248]:         <autogenerated>:1 +0x95 fp=0xc0002bdf48 sp=0xc0002bdf08 pc=0xa6e125
Jun 18 12:16:45 coordinator dcrpool[5248]: net/http.Handler.ServeHTTP-fm(0x11a90a0, 0xc00060f420, 0xc0001a6600)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/net/http/server.go:86 +0x65 fp=0xc0002bdf80 sp=0xc0002bdf48 pc=0xa6f635
Jun 18 12:16:45 coordinator dcrpool[5248]: net/http.(*http2serverConn).runHandler(0xc0006e3680, 0xc00060f420, 0xc0001a6600, 0xc0005389e0)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/net/http/h2_bundle.go:5658 +0x97 fp=0xc0002bdfc0 sp=0xc0002bdf80 pc=0x9e5bc7
Jun 18 12:16:45 coordinator dcrpool[5248]: runtime.goexit()
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0002bdfc8 sp=0xc0002bdfc0 pc=0x4836c1
Jun 18 12:16:45 coordinator dcrpool[5248]: created by net/http.(*http2serverConn).processHeaders
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/net/http/h2_bundle.go:5392 +0x918
Jun 18 12:16:45 coordinator dcrpool[5248]: goroutine 1 [semacquire, 1008 minutes]:
Jun 18 12:16:45 coordinator dcrpool[5248]: sync.runtime_Semacquire(0xc0001264a8)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/runtime/sema.go:56 +0x39
Jun 18 12:16:45 coordinator dcrpool[5248]: sync.(*WaitGroup).Wait(0xc0001264a0)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /usr/local/go/src/sync/waitgroup.go:130 +0xb2
Jun 18 12:16:45 coordinator dcrpool[5248]: github.com/decred/dcrpool/network.(*Hub).Run(0xc0001263c0, 0x11ab3e0, 0xc0000763c0)
Jun 18 12:16:45 coordinator dcrpool[5248]:         /home/dnldd/Work/dcrpool/network/hub.go:837 +0x1ff
Jun 18 12:16:45 coordinator dcrpool[5248]: main.main()
Jun 18 12:16:45 coordinator dcrpool[5248]:         /home/dnldd/Work/dcrpool/pool.go:215 +0x646
Jun 18 12:16:45 coordinator dcrpool[5248]: goroutine 22 [syscall, 1008 minutes]:
...
```

**Comment by jrick** [comment]
Since this is faulting on a non-nil address, I would suspect there is a data race somewhere that is corrupting memory.

**Comment by dnldd** [comment]
Looks like the modifications made to the gui bit sorted this out, been monitoring the mainnet test instance for a while now for bugs. Haven't caught anything in weeks. Would like to be certain before closing this however. Leaving it open.

**Comment by jholdstock** [comment]
I saw this error whilst running this commit https://github.com/decred/dcrpool/commit/02316c25888848fd9e131a69c91e9268a47e9903

hence why I created the PR updating the dependencies

**Comment by jholdstock** [comment]
This just happened again while I was running https://github.com/decred/dcrpool/commit/d2181e147fa7aa0533dd481b56ec67f359a8592b with a few local changes (only GUI files changed)

Here is the dcrpool output [seg fault.log](https://github.com/decred/dcrpool/files/3422641/seg.fault.log)

**Comment by jholdstock** [comment]
It happened again, and this time i was running the go.mod changes proposed in #108 

[error2.log](https://github.com/decred/dcrpool/files/3423144/error2.log)

**Comment by jrick** [comment]
build with `-race` and check the output for any discovered data races.

**Comment by dnldd** [comment]
I'm on my third run with `-race` and I still haven't reproduced it locally.

**Comment by dnldd** [comment]
Did some more testing after updating my build. Still cannot reproduce this issue, I restarted the pool several times running the harness as suggested, no dice. Shifting focus.

**Comment by jrick** [comment]
@jholdstock please test with a `-race` built binary since you are the only one that is hitting this.

**Comment by jholdstock** [comment]
Found a race, fixed in #122. Seems to be unrelated because even with the fix, the crash above is still happening. No further races detected

**Comment by jrick** [comment]
How about with `-msan` (to enable the LLVM memory sanitizer)?

**Comment by jholdstock** [comment]
Tried this, the crash still occurs and the output appears to be the same: 
[error3.log](https://github.com/decred/dcrpool/files/3480955/error3.log)
